name: hilarity-server
version: 0.1.0.0
github: "shadowmanu/hilarity-server"
license: MIT
author: "Manuel Pacheco"
maintainer: "manuelalejandropm@gmail.com"
copyright: "2021 Manuel Pacheco"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/shadowmanu/hilarity-server#readme>

dependencies:
  - base >= 4.14 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - containers
    - lens
    - random
    - stm
    - text
    - transformers
    - websockets

executables:
  hilarity-server-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hilarity-server

tests:
  hilarity-server-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hilarity-server
