name: hilarity-server
version: 0.1.0.0
github: "shadowmanu/hilarity-server"
license: MIT
author: "Manuel Pacheco"
maintainer: "manuelalejandropm@gmail.com"
copyright: "2019 Manuel Pacheco"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/shadowmanu/hilarity-server#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hilarity-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hilarity-server
      - aeson
      - containers
      - lens
      - random
      - stm
      - text
      - transformers
      - websockets

tests:
  hilarity-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hilarity-server
